permalink: /:categories/:title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "assets/css"
    values:
      layout: ""
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
sass:
  style: :compressed
markdown: kramdown
gems:
  - jekyll-sitemap